### ISSUE TITLE
Probljem

### ISSUE THREAD

**Issue by MrBombastic420** [ImDaMilan/mcdiscordannouncer#1]
I hev no discord server dont now how to yuse this mod. Pljz heljp me

**Comment by ImDaMilan** [comment]
To use the plugin, you're gonna have to have a Discord server, the whole point of the plugin is for it to inform the players on the Discord server on when the server is up/down. You are going to have to make a Discord server and go trough the setting up steps to use the plugin.

**Comment by MrBombastic420** [comment]
This mod gljiva bot dont work on my discird server i payd 3$ for yu skam me!
